Algoritmo "ex2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Edilma di Bindá
// Autor(a)    : Pedro de Sene Gouveia
// Data atual  : 25/05/2023
Var
gasto, salario: real


Inicio
escreval("Digite seu salário.")
leia(salario)
escreval("Digite seu gasto.")
leia(gasto)
se salario > gasto entao
escreval("Seu saldo será positivo.")
senao
escreval("Seu saldo será negativo.")
fimse



Fimalgoritmo