Algoritmo "ex3"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Edilma di Bindá
// Autor(a)    : Pedro de Sene Gouveia
// Data atual  : 25/05/2023
Var
idade: real
nome: caractere

Inicio
escreval("Digite seu nome.")
leia(nome)
escreval("Digite sua idade.")
leia(idade)
se idade >= 18 entao
escreval("A pessoa ",nome,", é maior de idade.")
senao
escreval("A pessoa ",nome,", é maior de idade.")
fimse



Fimalgoritmo