algoritmo "ex8"
// Autor : Pedro de Sene Gouveia
// Data : 02/06/2023
// Seção de Declarações 
var
mencao: caractere

inicio
escreval("Digite a menção.")
leia(mencao)
se (mencao = "I") ou (mencao = "i") ou (mencao = "R") ou (mencao = "r") entao
escreval("Você foi retido.")
fimse
se (mencao = "B") ou (mencao = "b") ou (mencao = "MB") ou (mencao = "mb") entao
escreval("Você foi aprovado.")
fimse
fimalgoritmo
