Algoritmo "cotacaodolar"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Edilma Bindá
// Autor(a)    : Pedro Sene
// Data atual  : 30/03/2023
Var
dolar, cotacao, reais: real


Inicio
escreval ("Digite a cotacão do dólar")
leia (cotacao)
escreval ("Digite o valor a ser convertido em dólar")
leia (reais)
dolar <- reais*cotacao
escreval ("O dinheiro em dólar é de ",dolar,".")s


Fimalgoritmo