Algoritmo "exercicio5"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Edilma Bindá
// Autor(a)    : Pedro de Sene
// Data atual  : 07/04/2023
Var
horas, minutos, segundostt: real


Inicio
escreval ("Digite as horas")
leia (horas)
escreval ("Digite os minutos")
leia (minutos)
segundostt <- (horas*60+minutos)*60
escreval ("",horas,"h e",minutos,"m tem ",segundostt," segundos.")




Fimalgoritmo