Algoritmo "mediacombgasto"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Edilma Bindá
// Autor(a)    : Pedro de Sene
// Data atual  : 09/03/2023
Var
comb, km, med: real


Inicio
escreval ("Digite a distância percorrida(em KM).")
leia (km)
escreval ("Digite o combustível gasto(em litros).")
leia (comb)
med <- comb/km
escreval ("O consumo médio de combústivel foi de ",med," litros gastos por km.")


Fimalgoritmo