Algoritmo "areaeperdoretangulo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Edilma Bindá
// Autor(a)    : Pedro de Sene
// Data atual  : 09/03/2023
Var
base, alt, area, per: real


Inicio
escreval ("Digite o valor da base do retângulo.")
leia (base)
escreval ("Digite o valor da altura do retângulo.")
leia (alt)
area <- base*alt
per <-  (base+alt)*2
escreval ("A área é de",area," e o perímetro é de ",per,".")

Fimalgoritmo